"undefined"==typeof amkit&&(amkit=function(){var c=amkit.util.makeArray(arguments);return arguments.callee.use.apply(this,c)});(function(c){c=c.config={};c.debug=!1;c.charset="utf-8";c.base="";c.alias={};c.preload=[]})(amkit);
(function(c){var h=Object.prototype.toString,e=Array.prototype;c.util=function(){return{isNumber:function(b){return"number"===typeof b},isString:function(b){return"[object String]"===h.call(b)},isFunction:function(b){return"[object Function]"===h.call(b)},isRegExp:function(b){return"[object RegExp]"===h.call(b)},isObject:function(b){return b===Object(b)},isArray:Array.isArray||function(b){return"[object Array]"===h.call(b)},makeArray:function(b){if(null==b)return[];if(c.util.isArray(b))return b;if("number"!==
typeof b.length||b.alert||c.util.isString(b)||c.util.isFunction(b))return[b];for(var e=[],f=0,h=b.length;f<h;f++)e[f]=b[f];return e},indexOf:e.indexOf?function(b,c){return b.indexOf(c)}:function(b,c){for(var e=0;e<b.length;e++)if(b[e]===c)return e;return-1},forEach:e.forEach?function(b,c){b.forEach(c)}:function(b,c){for(var e=0;e<b.length;e++)c(b[e],e,b)},filter:e.filter?function(b,c){return b.filter(c)}:function(b,e){var f=[];c.util.forEach(b,function(b,c,d){e(b,c,d)&&f.push(b)});return f},map:e.map?
function(b,c){return b.map(c)}:function(b,e){var f=[];c.util.forEach(b,function(b,c,d){f.push(e(b,c,d))});return f}}}()})(amkit);
(function(c){function h(a){a=a.match(i);return(a?a[0]:".")+"/"}function e(a){l.lastIndex=0;l.test(a)&&(a=a.replace(l,"$1/"));if(-1===a.indexOf("."))return a;for(var b=a.split("/"),c=[],g,e=0;e<b.length;e++)if(g=b[e],".."===g){if(0===c.length)throw Error("The path is invalid: "+a);c.pop()}else"."!==g&&c.push(g);return c.join("/")}function b(a){var a=e(a),b=a.charAt(a.length-1);if("/"===b)return a;"#"===b?a=a.slice(0,-1):-1===a.indexOf("?")&&!s.test(a)&&(a+=".js");0<a.indexOf(":80/")&&(a=a.replace(":80/",
"/"));return a}function m(a){if("#"===a.charAt(0))return a.substring(1);var b=c.config.alias;if(b&&n(a)){var e=a.split("/"),g=e[0];b.hasOwnProperty(g)&&(e[0]=b[g],a=e.join("/"))}return a}function f(a){return 0<a.indexOf("://")||0===a.indexOf("//")}function q(a){return"/"===a.charAt(0)&&"/"!==a.charAt(1)}function n(a){var b=a.charAt(0);return-1===a.indexOf("://")&&"."!==b&&"/"!==b}var d=c.util,i=/.*(?=\/.*$)/,l=/([^:\/])\/\/+/g,s=/\.(?:css|js)$/,t=/^(.*?\w)(?:\/|$)/,o={},k=window.location,j=k.protocol+
"//"+k.host+function(a){"/"!==a.charAt(0)&&(a="/"+a);return a}(k.pathname);0<j.indexOf("\\")&&(j=j.replace(/\\/g,"/"));d.dirname=h;d.realpath=e;d.normalize=b;d.parseAlias=m;d.parseMap=function(a){var b=c.config.map||[];if(!b.length)return a;for(var e=a,g=0;g<b.length;g++){var p=b[g];if(d.isArray(p)&&2===p.length){var i=p[0];if(d.isString(i)&&-1<e.indexOf(i)||d.isRegExp(i)&&i.test(e))e=e.replace(i,p[1])}else d.isFunction(p)&&(e=p(e))}e!==a&&(o[e]=a);return e};d.unParseMap=function(a){return o[a]||
a};d.resolve=function(a,e){if(!a)return"";a=m(a);e||(e=j);var r;if(f(a))return a;0===a.indexOf("./")||0===a.indexOf("../")?(0===a.indexOf("./")&&(a=a.substring(2)),r=h(e)+a):r=q(a)?e.match(t)[1]+a:c.config.base+"/"+a;return b(r)};d.isAbsolute=f;d.isRoot=q;d.isTopLevel=n;d.pageUri=j})(amkit);(function(c){c.util.log=function(c){console&&console.log(c)}})(amkit);
(function(c){var h,e=c.util;h=2;var b={},m={},f=null,q=function(){},n=function(b,e,c,d){this.id=b;this.deps=e||[];this.factory=c||q;this.status=d||0};n.prototype={compile:function(c){var d=this.factory,f=this.ecports,h=this.deps||[];c||(c=[this.id]);if(3==this.status)return this.exports;h=e.map(h,function(b){return e.resolve(b)});if(f)return f;f=e.map(h,function(d){d=e.resolve(d);if(-1<e.indexOf(c,d))b[d].exports;else return c.push(d),d?b[d].compile(c):null});this.exports=f=d.apply(null,f);this.status=
3;return f}};var d=function(){var d=document,l=d.head||d.getElementsByTagName("head")[0]||d.documentElement,s=/\.css(?:\?|$)/i,t=/loaded|complete|undefined/,o=navigator.userAgent,k=null,j=null;return{add:function(a,b){var c=arguments;if(0!=c.length){if(1==c.length||!b)b=a,a=[];e.isArray(a)||(a=[a]);var c={deps:a,factory:b},g="";if(document.attachEvent){var d=this._getCurrentScript();d&&(g=e.unParseMap(this._getScriptAbsoluteSrc(d)));g&&this.saveModule(new n(g,a,b))}else f=c;return c}},load:function(a,
c,d){var g=this;if(e.isString(a))a=e.resolve(a),d||(d=[a]),g._load(a,function(){var f=b[a].deps||[],f=e.filter(f,function(a){a=e.resolve(a);return-1<e.indexOf(d,a)?!1:!0});e.forEach(f,function(a){a=e.resolve(a);d.push(a)});f&&0<f.length?g.load(f,c,d):c()});else if(e.isArray(a)){var f=a.length,j=f;if(0==f)c();else for(var h=function(){j--;0==j&&c()},i=0;i<f;i++)g.load(a[i],h,d)}},saveModule:function(a){b[a.id||""]=a},ignore:function(a){var d=c.ignoreModuleMeta;deps=d.deps;factory=d.factory;uri=e.resolve(a);
module=b[uri]||new n(uri,deps,factory,2);this.saveModule(module);c.ignoreModuleMeta=null},_getModule:function(a){return b[a]||null},_load:function(a,d){function j(){var b=g._getCallback(a),c=0,e=b.length;f&&(i.deps=f.deps,i.factory=f.factory,f=null);for(i.status=h;c<e;c++)b[c].call(null)}var g=this,i,l=c.config.charset,a=e.resolve(a);i=b[a]||new n(a);g.saveModule(i);i.status>=h?d():1<=i.status?g._saveCallback(a,d):(i.status=1,g._saveCallback(a,d),s.test(a)?this._loadStyle(a,function(){j()},l):this._loadScript(a,
function(){j()},l))},_saveCallback:function(a,b){m[a]?m[a].push(b):m[a]=[b]},_getCallback:function(a){(a=m[a])||(a=[]);return a},_loadScript:function(a,b,e){var d=document.createElement("script");d.charset=e;d.onload=d.onerror=d.onreadystatechange=function(){t.test(d.readyState)&&(d.onload=d.onerror=d.onreadystatechange=null,d.parentNode&&!c.config.debug&&l.removeChild(d),d=void 0,b())};d.src=a;k=d;l.appendChild(d);k=null},_loadStyle:function(a,b,c){var d=document.createElement("link");d.rel="stylesheet";
d.charset=c;var f=this,c=536>Number(o.replace(/.*AppleWebKit\/(\d+)\..*/,"$1")),i=0<o.indexOf("Firefox")&&!("onload"in document.createElement("link"));c||i?(e.log("Start poll to fetch css"),setTimeout(function(){f._poll(d,b)},1)):d.onload=d.onerror=function(){d.onload=d.onerror=null;d=void 0;b()};d.href=a;k=d;l.appendChild(d);k=null},_poll:function(a,b){var c,d=this;if(isOldWebKit)a.sheet&&(c=!0);else if(a.sheet)try{a.sheet.cssRules&&(c=!0)}catch(e){"NS_ERROR_DOM_SECURITY_ERR"===e.name&&(c=!0)}setTimeout(function(){c?
b():d._poll(a,b)},1)},_getCurrentScript:function(){if(k)return k;if(j&&"interactive"===j.readyState)return j;for(var a=l.getElementsByTagName("script"),b=0;b<a.length;b++){var c=a[b];if("interactive"===c.readyState)return j=c}},_getScriptAbsoluteSrc:function(a){return a.hasAttribute?a.src:a.getAttribute("src",4)}}}();c.use=function(f,h){function m(c){return e.map(c,function(a){return a?b[a].compile():null})}var n=c.util.makeArray(arguments).length,o=c.config.preload||[];if(0!=n){1==n&&(h=q);e.isString(f)&&
(f=[f]);var k=e.map(f,function(b){return e.resolve(b)}),o=e.map(o,function(b){return e.resolve(b)});d.load(o,function(){c.config.preload=[];m(o);d.load(k,function(){var b=m(k);h&&h.apply(null,b)})})}};c.add=function(b,e){c.ignoreModuleMeta=d.add(b,e);return c};c.ignore=function(b){d.ignore(b)};c.cache=b})(amkit);
